#!/bin/bash

#Include enviroment variables
. $(cd `dirname "${BASH_SOURCE[0]}"` && pwd)/subutai.env

umount $1

mkfs.btrfs -f $1

echo "[Unit]
Description = BTRFS mount

[Mount]
What = $1
Where = /var/snap/subutai/common/lxc 
Type = btrfs

[Install]
WantedBy = multi-user.target" > $SUBUTAI_SYS_ETC/systemd/system/var-snap-subutai-common-lxc.mount

systemctl daemon-reload
systemctl start var-snap-subutai-common-lxc.mount
systemctl enable var-snap-subutai-common-lxc.mount

mkdir -p /var/snap/subutai/common/lxc/tmpdir

$SUBUTAI_APP_PREFIX/bin/btrfs quota enable /var/snap/subutai/common/lxc/tmpdir
